### PR TITLE
show 7 days per week in docs, fixes #12

### LINKED ISSUE #12: Heatmap height too small in docs
https://github.com/frappe/charts/blob/4bb44c0914125e4b511592623870946bdac3f0a8/docs/index.html#L218

It’s hiding the seventh day each week. Should be 115px.

### PR DESCRIPTION
**Pull request by jakob-stoeck**
Now you can’t hide anymore that you don’t commit on Sundays ;)

### CODE REVIEW

**Comment by achillesrasquinha** [comment]
Lol. We at @frappe use the Heatmap to check daily attendance of entities within our product github.com/frappe/erpnext

Maybe that's why we never thought of Sundays! 😛

Just add in a Screenshot to your PR (This is our fault, we'll be working on contribution guidelines) and we'll have it merged! 

Thanks!

**Comment by pratu16x7** [comment]
@jakob-stoeck 
Test then whether Sundays appear. Would be awesome if you post before and after screenshots :)

**Comment by iDemonix** [comment]
If you are updating these files, here's what I'm doing for my test project to show dummy data:

```
	let heatmap_data = {};
	let current_date = new Date();
	let timestamp = current_date.getTime()/1000;
	timestamp = Math.floor(timestamp - (timestamp % 86400)).toFixed(1); // convert to midnight
	for (var i = 0; i< 375; i++) {
		heatmap_data[timestamp] = Math.floor(Math.random() * 6) + 1;
		timestamp = Math.floor(timestamp - 86400).toFixed(1);
	}
```

Which gives me a nice randomised set of data on reload:

image

**Comment by pratu16x7** [comment]
@iDemonix Send in a PR!

**Comment by iDemonix** [comment]
I'm looking forward to seeing your contribution docs and so on :) I've only recently picked up Javascript and have not much knowledge around compiling/minifying/testing etc. Once your doc is out I'll give it a read and hopefully I can submit some of my first PRs!

**Pull request merged**
