### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by clickthisnick**
###### Explanation About What Code Achieves:

  - Adds a pull request template so code review is easier for maintainers

###### Steps To Test:

  - Create a pull request and this template will show

###### TODOs:

  - None

### CODE REVIEW

**Comment by achillesrasquinha** [comment]
Hi, could you name it CONTRIBUTION.md instead? I guess GitHub automatically has it detected for new contributors.

**Comment by clickthisnick** [comment]
`CONTRIBUTION.md` and `PULL_REQUEST_TEMPLATE.md` serve two different purposes.

The `CONTRIBUTION.md` is a guideline for new contributors on how to contribute to the project. It may include sla signoffs, coding patterns, testing requirements, etc.
https://github.com/blog/1184-contributing-guidelines

The `PULL_REQUEST_TEMPLATE.md` is a template that inserted into the body whenever a pull request gets created. Its useful for the maintainer, so that they have more information about why the pull request is needed. This reduces the burden on the maintainer to figure out the thought process behind the pull request.
https://github.com/blog/2111-issue-and-pull-request-templates

Please let me know if you still want it renamed CONTRIBUTION.md
Thanks!

**Comment by achillesrasquinha** [comment]
Alright! Let's add this then.

Thanks.

**Comment by clickthisnick** [comment]
Yup, added `.github`

**Comment by achillesrasquinha** [comment]
Great, thanks! Merging.

**Pull request merged**
