### PR TITLE
invert gradient direction when all negative

### PR DESCRIPTION
**Pull request by t47io**
###### Explanation About What Code Achieves:
When there is a dataset that is all non-positive, the gradient direction should ideally be inverted.

###### Screenshots/GIFs:
BEFORE:
screen shot 2017-12-20 at 5 50 50 pm
AFTER:
screen shot 2017-12-20 at 5 55 14 pm

###### Steps To Test:
Get a dataset that with no positive values, and check the direction of the gradient.

### CODE REVIEW

**Comment by t47io** [comment]
@pratu16x7 I can adapt this PR for the 1.x branch. What's your thoughts for incorporating this?

**Comment by pratu16x7** [comment]
@t47io 

I think the amount of gradient color defines the real _numeric_ value of the points, rather than the _magnitude_ (or absolute value). So if the number is more negative, even amongst a set of all negative numbers, it makes sense if it gets the least color of all.

Your thoughts?

**Comment by pratu16x7** [comment]
@t47io @ferrelucas @tomarrell

I think the amount of gradient color defines the real numeric value of the points, rather than the magnitude (or absolute value). So if the number is more negative, even amongst a set of all negative numbers, it makes sense if it gets the least color of all.

Your thoughts?

**Comment by t47io** [comment]
I find it counter-intuitive at least for my use case. But if both are possible use cases, we should maybe consider adding it as an option or something.

**Comment by tomarrell** [comment]
I feel like especially choosing a complimentary color, you would certainly expect a more negative number to be more red, representing a proper flow between green (high values), white (neutral/central values) and red (increasingly negative values). At least by default.

The sudden loss of color moving upwards appears jarring and counter-intuitive, as if it were unintentional.

I'd have to say I'm with @t47io on this one as default behaviour.

**Comment by scmmishra** [comment]
The changes on these have drifted away from the latest version, LineChart file itself is diverged a lot. Closing this PR

**Pull request closed without merging**
