### PR TITLE
add js/charts/BaseChart - unbind_window_events

### PR DESCRIPTION
**Pull request by FlorianBELLAZOUZ**
When we use virtualdom like snabbdom for exemple,
We need to unbind window events at each destroy hook.

This PR add an unbind_window_events at BaseChart.

### CODE REVIEW

**Comment by t47io** [comment]
Yes, I saw a flood of errors when using `frappe/charts` with React. So @FlorianBELLAZOUZ once this PR is merged, I guess the desired way is to manually call `unbind_window_events()` on `componentWillUnmount()` right?

**Comment by FlorianBELLAZOUZ** [comment]
Exact ! and you can use it now if you want !

Just update frappe-charts in your package.json :
``"frappe-charts": "florianbellazouz/charts#unbind_window_events"``

**Comment by t47io** [comment]
@pratu16x7 could you guys take a look at this PR (and other open ones) and incorporate into a frappe-charts release? looking forward to see it improves!~ thanks

**Comment by brandonparsons** [comment]
Commenting here as I'm also interested in upgrading to a new version that contains this patch.

**Comment by t47io** [comment]
@pratu16x7 @achillesrasquinha @raghukamath maintainers please?

**Comment by pratu16x7** [comment]
@FlorianBELLAZOUZ 

Just made a commit on `develop` to address this https://github.com/frappe/charts/commit/6ed4820a70b23f54d2f84bcda74d228ba1c8ccb9

**Comment by scmmishra** [comment]
FIxed this in the recent release https://github.com/frappe/charts/commit/92674f94f19e4c784d501125f7c454e246f9d1b9

Closing this PR

**Pull request closed without merging**
